### ISSUE TITLE
Responsiveness broken for Add to cart

### ISSUE THREAD

**Issue by st-schneider** [thanhchungbtc/vue-shopping-clean-architecture#2]
![image](https://user-images.githubusercontent.com/30625381/75655033-4bb5a500-5c61-11ea-85b4-7ede52442af0.png)

**Comment by thanhchungbtc** [comment]
Thank you for opening the issue.
I see it happens at a very small screen size (~ 200px), that in my opinion, not practical.
I have no idea which use-case of such a device is and how to change the design to adapt.
Any suggestion?

**Comment by st-schneider** [comment]
for the demo, this happens on 1244 already

**Comment by thanhchungbtc** [comment]
The problem was that the tool I use to generate the GitHub page automatically append some layout stuff to the demo while it should be on an independent page.
I have fixed  but you might want to clear cache before it'll be reflected 
(Open Chrome Devtool Application/Clear storage)
